name: Docker

on:
  push:
    branches:
      - master
    tags:
      - latest

jobs:
  build-and-push:
    name: Deploy Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        uses: openzim/docker-publish-action@v5
        with:
          image-name: causefx/sonarrchecker
          registries: ghcr.io
          credentials: |
            GHCRIO_USERNAME=${{ secrets.GH_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GH_TOKEN }}
          on-master: master
          latest-on-tag: true
          build-args:
            VERSION={tag}
          manual-tag: latest
